name: Atramhasis backend tests

on:
  pull_request:
    paths:
      - atramhasis/**
      - scripts/**
      - tests/**
      - "!atramhasis/static/**"
      - .github/workflows/backend.yaml
      - pyproject.toml
      - requirements*.txt

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install python requirements
        env:
          HATCH_BUILD_NO_HOOKS: true
        working-directory: ./
        run: |
          pip --version
          pip install --upgrade "pip<25.3"
          pip install pip-tools
          pip-sync requirements-dev.txt
          pip install -e .

      - name: Compile message catalogs
        run: pybabel compile --directory 'atramhasis/locale' --domain atramhasis --statistics true

      - name: Python tests
        run: pytest tests --exitfirst --capture=no -vvv --full-trace --cov-report xml:${{ runner.temp }}/coverage.xml --cov=atramhasis

      - name: Get Cover
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: ${{ runner.temp }}/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceDir: atramhasis
          thresholdAll: 0.9
          thresholdNew: 0.9
          thresholdModified: 0.8
